# Generated by Django 4.0.4 on 2022-05-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_account_first_name_alter_account_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
